params:
    dns_type: common

type: JsonStrInt  # Type of the data-form will be determined automatically in the future

substitutions:
    awsdns\-\d+: awsdns
    (.*)\.amazonaws\.com: '{}.amazonaws.org'
    sohosted\d+: sohosted

dns: << functions.hosting.nslookup(params.domain, params.dns_type, substitutions) >>

requires: << dns >>

index: # Index of the data-form, for querying and data-analysis.
    a1: << dns.generic.a1 >> -> str  # Currently, the type of the variable is explicit; will be derived from sample data in the future.
    a_fqdn1: << dns.generic.a_fqdn1 >> -> str
    ns1: << dns.generic.ns1 >> -> str
    mx1: << dns.generic.mx1 >> -> str

refresh:
    every: << "1 month" if not index.a1 else "3 months" >>
#    crontab: "30 12 * */2 sun"
    # Optionally, specify a crontab for fixed times.
    # format is https://en.wikipedia.org/wiki/Cron

json: << dns.generic >>
# Stored in the database, very limited querying (only equality/missing/present), presence in lists

file:
    summary.json:  # Multiple files with the same name, is only relevant when multiple access types are used.
        -   content: << dns.generic >>
            access: by-uuid  # only for someone who has the uuid of the item
        -   content: << dns.generic >>
            access: public  # public for everyone
            content-type: text/plain  # not correct, but to show the field
    full.json:  # sinlge file specified. access by default is private, content-type is derived from the file extension.
        content: << dns >>

simple-file:   # simple file only has name and content, access is private, content-type is automatic. Is identical to above spec in complete file spec.
    full.json: << dns >>

# Stored offline, for individual items to fetch, no querying, no presence in lists. Can be multiple files when a list
# is specified, are named explicitly

transient: null
# Not stored, only used for the current session, no querying, no presence in lists
