params:
    dns_type: common

type: JsonStrInt  # Type of the data-form will be determined automatically in the future

substitutions:
    awsdns\-\d+: awsdns
    (.*)\.amazonaws\.com: '{}.amazonaws.org'
    sohosted\d+: sohosted

dns: << f.sitekick.hosting.nslookup(domain, dns_type, substitutions) >>
dns1: << dns >>

index: # Index of the data-form, for querying and data-analysis.
    a1: << dns.generic.a1 >> -> str  # Currently, the type of the variable is explicit; will be derived from sample data in the future.
    a_fqdn1: << dns.generic.a_fqdn1 >> -> str
    ns1: << dns.generic.ns1 >> -> str
    mx1: << dns.generic.mx1 >> -> str

json: << dns.generic >>
# Stored in the database, very limited querying (only equality/missing/present), presence in lists

file: null
# Stored offline, for individual items to fetch, no querying, no presence in lists. Can be multiple files when a list
# is specified, are automatically named and optionally named explicitly

transient: null
# Not stored, only used for the current session, no querying, no presence in lists
